export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
export { default as Hero } from './Hero/Hero'
export { default as Skils } from './Skils/Skils'
export { default as Testimonials } from './Testimonials/Testimonials'
export { default as Work } from './Work/Work'
